feat: [CI-14878]: Use client certs for mTLS connection
harness/dlite pull request #32
Opened 2024-10-30 10:00 UTC by devkimittal

2024-11-04 05:09 UTC, anurag-harness requested changes

2024-11-04 05:09 UTC, anurag-harness commented on delegate/http.go
> +			fmt.Println(fmt.Errorf("error adding cert (%s) to pool, please check format of the certs provided", path))
Switch to log.Errorf. PR checks are failing

2024-11-04 16:22 UTC, vistaarjuneja commented
dlite is only used for hosted - do we need to make changes for mtls there as well? @devkimittal @anurag-harness

2024-11-04 17:21 UTC, anurag-harness commented
> dlite is only used for hosted - do we need to make changes for mtls there as well? @devkimittal @anurag-harness

We use the same client in k8 engine to send step status from engine to manager. The change is to support mtls in that

2024-11-05 06:56 UTC, anurag-harness approved these changes

2024-11-05 07:26 UTC, merged

2024-11-06 05:07 UTC, hemanthmantri commented on delegate/http.go
> +	if skipverify || rootCAs != nil || mtlsEnabled {
What is `skipVerify`?  Shouldn't this be  `if !skipVerify` ?